### ISSUE TITLE
MarkdownParser or CommonMarkParser

### ISSUE THREAD

**Issue by nsoranzo** [codejamninja/sphinx-markdown-parser#4]
It's not clear from the README why one should choose one over the other.

**Comment by clayrisser** [comment]
You should choose MarkdownParser because it's more feature rich (supports tables etc...). RecommonmarkParser is just for backwards compatibility with RecommonMark. If you really want to use RecommonMark, probably you should just use RecommonMark's extension instead.

https://github.com/readthedocs/RecommonMark

Again though, I would recommend this plugin with the MarkdownParser.
